### ISSUE TITLE
Unnecessary console.log

### ISSUE THREAD

**Issue by henriquecm** [reezpatel/seven-json-viewer#11]
The extension logs an error on console in all pages that aren't json

![image](https://user-images.githubusercontent.com/15136037/127705292-cf93d94b-ea44-4b71-ae46-751b44f80737.png)

**Comment by reezpatel** [comment]
This is fixed with a new version written in svelte from scratch for improved performance. It's already present in chrome web store. I have also just published it in edge extension store, it will be approved in a couple of days. Do give it a try once again.
