### ISSUE TITLE
Extension crashes while writing json path query  

### ISSUE THREAD

**Issue by Danysan1** [reezpatel/seven-json-viewer#13]
If a parenthesis is opened in the json-path field the extension crashes. For example:

1. Go to https://www.gstatic.com/ipranges/cloud.json with the extension installed
2. `$.prefixes[?(@.ipv4Prefix == "130.211.96.0/20")].scope` is a valid query for this file, and if you copy-paste it in the cell it works
3. Try writing it by hand, once you arrive at `$.prefixes[?(` the extension crashes and in the console you can see this: ![image](https://user-images.githubusercontent.com/8406735/134925249-ed8a9a1e-3c8f-4ccc-a756-f656fa89fe5d.png)
4. In order to do anything you have to reload the page

Similarly, any temporary bad query makes the extension crash.

I am experiencing this with version 2.1 on Edge 94.0.992.31

**Comment by reezpatel** [comment]
This is fixed with a new version written in svelte from scratch for improved performance. It's already present in chrome web store. I have also just published it in edge extension store, it will be approved in a couple of days. Do give it a try once again.
