### ISSUE TITLE
The extension doesn't work

### ISSUE THREAD

**Issue by desbest** [reezpatel/seven-json-viewer#16]
Hello your extension doesn't work. When I open these .json files, I don't get any syntax highlighting or code beautifying/prettifying.

Are you only looking for the Content-Type HTTP header and not the file extension?

Try it yourself and test it out with these URL's

https://raw.githubusercontent.com/HuiiBuh/InstagramDownloader/master/src/tsconfig.json

https://gitlab.com/-/snippets/2385140/raw/main/pictureflect%20saved%20effect%20list.json

**Comment by reezpatel** [comment]
Can you tell me which browser are you using? I clicked on both the links and both of them are working for me..

**Comment by desbest** [comment]
Microsoft Edge 103

**Comment by reezpatel** [comment]
Ok thanks for that, I have submitted the latest version of extension to Microsoft store, It will take a couple of days to get it approved, meanwhile you can install latest version of extension from chrome web store.

**Comment by desbest** [comment]
Hello it still doesn't work. See the images below.
There is no syntax highlighting and code prettifying/beautifying.
I'm using Microsoft Edge 105

![seven json viewer doesn't work 2](https://user-images.githubusercontent.com/1139316/189139162-7639770e-5fa4-4c42-b92a-0d8b26736c2c.png)

![seven json viewer doesn't work 1](https://user-images.githubusercontent.com/1139316/189139171-916ddb2c-0e11-45d5-921f-9a9217dc7527.png)
