### ISSUE TITLE
Update colors to match screenshots

### ISSUE THREAD

**Issue by zstix** [reezpatel/seven-json-viewer#5]
## Description
First off, thanks for developing this awesome extension - it's really helpful.

That said, I wish the color scheme would match those wonderful screenshots you've created (see screenshot below).

Additionally, it would be rad for the user to be able to choose a theme or customize it themselves.

## Screenshot(s)
Left = screenshot | Right = reality
![Screen Shot 2020-12-10 at 2 00 17 PM](https://user-images.githubusercontent.com/1946433/101835648-ef858880-3af0-11eb-9bdb-dc7eff4e6d92.png)

**Comment by reezpatel** [comment]
Released v3.0.0, it should get published within a week. Added dark & light theme for now, more to come soon.
